language: python

branches:
  only:
  - master

python:
  - '3.7'
  - '3.6'
  
 jobs:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python" --version 3.7.4
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel

install:
  - pip install -r requirements.txt
  - pip install -U pytest pytest-cov codecov pycodestyle

script:
  - pytest tests/ --cov=./mvlearn/
  - pycodestyle mvlearn/

after_success:
  - codecov
