language: python

branches:
  only:
  - master

python:
  - '3.8'
  - '3.7'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install -r requirements_torch.txt
  - pip install -U pytest pytest-cov codecov pycodestyle

script:
  - pytest tests/ --cov=./mvlearn/
  - pycodestyle mvlearn/

after_success:
  - codecov
